C_Shop_Class_20220522/Models/ErrorViewModel.cs
namespace C_Shop_Class_20220522.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

C_Shop_Class_20220522/Models/Family.cs
using System.ComponentModel.DataAnnotations;

namespace C_Shop_Class_20220522.Models
{
    public class Family
    {
        // 驗證屬性
        // Validation Attribute
        [Required]
        [Range(1, 1000)]
        [Display(Name = "No.")]
        public int? Id { get; set; }
        [Required]
        [Display(Name = "姓名")]
        public string? Name { get; set; }
        [Required]
        [Range(0, 100)]
        [Display(Name = "年齡")]
        public int? Age { get; set; }
        [Required]
        [Display(Name = "稱謂")]
        public string? Title { get; set; }
        [Display(Name = "暱稱")]
        public string? NickName { get; set; }
    }

    public class FamilyInfo
    {
        public List<Family> _familyList = new List<Family>();

        public Family family = new Family();
        public FamilyInfo(List<Family> families)
        {
            _familyList = families;
        }
        public void FamilyDetail(bool submitstatus,  Family submit)
        {
            if (submitstatus)
            {                
                family = submit;
            }
            else
            {
                family.Id = _familyList.Max(x => x.Id) + 1;
            }
        }
    }
}

C_Shop_Class_20220522/Models/Hero.cs
using System.ComponentModel.DataAnnotations;

namespace C_Shop_Class_20220522.Models
{
    public class Hero
    {
        // 驗證屬性
        // Validation Attribute
        [Required]
        [Range(1, 1000)]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Range(0, 100)]
        public int Atk { get; set; }
        [Required]
        [Range(1, 100)]
        public int Hp { get; set; }
    }
}

C_Shop_Class_20220522/Controllers/FamilyController.cs
using C_Shop_Class_20220522.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace C_Shop_Class_20220522.Controllers
{
    public class FamilyController : Controller
    {
        private static List<Family> families = new List<Family>()
            {
            new Family(){ Name="張曉明", Title="爸爸", Id=1, Age=55, NickName="大張" },
            new Family(){ Name="黃小鴨", Title="媽媽", Id=2, Age=50, NickName="大黃" },
            new Family(){ Name="張非", Title="本人", Id=3, Age=18, NickName="小張" },
            new Family(){ Name="張胡", Title="弟弟", Id=4, Age=8, NickName="小小張" },
            };
        // GET: FamilyController
        public ActionResult Index()
        {
            var result = new FamilyInfo(families);
            return View(result._familyList);
        }

        // GET: FamilyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FamilyController/Create
        public ActionResult Create()
        {
            var Info = new FamilyInfo(families);
            Info.FamilyDetail(false, null);
            return View(Info.family);
        }

        // POST: FamilyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Family submit)
        {
            try
            {
                var family = new FamilyInfo(families);
                family.FamilyDetail(true, submit);
                families.Add(family.family);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FamilyController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FamilyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FamilyController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FamilyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

C_Shop_Class_20220522/Controllers/HeroController.cs
using C_Shop_Class_20220522.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace C_Shop_Class_20220522.Controllers
{
    public class HeroController : Controller
    {

        private static List<Hero> _heroes = new List<Hero>()
        {
            new Hero(){Id = 1, Name = "鋼鐵人", Atk = 50, Hp = 100},
            new Hero(){Id = 2, Name = "索爾", Atk = 50, Hp = 100}
        };
        // GET: HeroController
        public ActionResult Index()
        {
            var heroes = _heroes.ToList();
            return View(heroes);
        }

        // GET: HeroController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HeroController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HeroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Hero model)
        {
            try
            {
                _heroes.Add(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HeroController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HeroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HeroController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HeroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

C_Shop_Class_20220522/Controllers/HomeController.cs
using C_Shop_Class_20220522.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace C_Shop_Class_20220522.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C_Shop_Class_20220522/Views/Family/Create.cshtml
@model C_Shop_Class_20220522.Models.Family

@{
    ViewData["Title"] = "新增家人";
}

<h1>@ViewData["Title"]</h1>

<h4>Family</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NickName" class="control-label"></label>
                <input asp-for="NickName" class="form-control" />
                <span asp-validation-for="NickName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

C_Shop_Class_20220522/Views/Family/Index.cshtml
@model IEnumerable<C_Shop_Class_20220522.Models.Family>

@{
    ViewData["Title"] = "家人清單";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">新增</a>
</p>
<table class="table table-hover dataTable dtr-inline">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NickName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NickName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

C_Shop_Class_20220522/Views/Hero/Create.cshtml
@model C_Shop_Class_20220522.Models.Hero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Atk" class="control-label"></label>
                <input asp-for="Atk" class="form-control" />
                <span asp-validation-for="Atk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hp" class="control-label"></label>
                <input asp-for="Hp" class="form-control" />
                <span asp-validation-for="Hp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

C_Shop_Class_20220522/Views/Hero/Index.cshtml
@model IEnumerable<C_Shop_Class_20220522.Models.Hero>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Atk)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hp)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Atk)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hp)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

C_Shop_Class_20220522/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

C_Shop_Class_20220522/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - C_Shop_Class_20220522</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/C_Shop_Class_20220522.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C_Shop_Class_20220522</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hero" asp-action="Index">Hero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Family" asp-action="Index">Family</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - C_Shop_Class_20220522 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>